[assembly: System.Reflection.AssemblyCompanyAttribute("Kimserey Lam")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Sqlite Healh Check extension to be used with Groomgy Health Check library for ASP.NET Core")]
[assembly: System.Reflection.AssemblyProductAttribute("Groomgy.HealthChecks.AspNetCore.Sqlite")]
[assembly: System.Reflection.AssemblyTitleAttribute("Groomgy.HealthChecks.AspNetCore.Sqlite")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0")]